// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package Event.ds;

public interface ResponseMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.ResponseMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();
}
