// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.service1;

public final class Service1Impl {
  private Service1Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_RequestMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_RequestMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_ResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_ResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016service1.proto\022\010service1\"4\n\016RequestMes" +
      "sage\022\020\n\010username\030\001 \001(\t\022\020\n\010password\030\002 \001(\t" +
      "\"\037\n\017ResponseMessage\022\014\n\004code\030\001 \001(\0052P\n\010Ser" +
      "vice1\022D\n\013service1_do\022\030.service1.RequestM" +
      "essage\032\031.service1.ResponseMessage\"\000B\035\n\013d" +
      "s.service1B\014Service1ImplP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_service1_RequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service1_RequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_RequestMessage_descriptor,
        new String[] { "Username", "Password", });
    internal_static_service1_ResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service1_ResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_ResponseMessage_descriptor,
        new String[] { "Code", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
