// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package Calendar.ds.service2;

public interface AppointmentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.AppointmentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .service2.Appointment appointments = 1;</code>
   */
  java.util.List<Appointment>
      getAppointmentsList();
  /**
   * <code>repeated .service2.Appointment appointments = 1;</code>
   */
  Appointment getAppointments(int index);
  /**
   * <code>repeated .service2.Appointment appointments = 1;</code>
   */
  int getAppointmentsCount();
  /**
   * <code>repeated .service2.Appointment appointments = 1;</code>
   */
  java.util.List<? extends AppointmentOrBuilder>
      getAppointmentsOrBuilderList();
  /**
   * <code>repeated .service2.Appointment appointments = 1;</code>
   */
  AppointmentOrBuilder getAppointmentsOrBuilder(
      int index);
}
