// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package Calendar.ds.service2;

public interface eventIdListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.eventIdList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 eventIds = 1;</code>
   * @return A list containing the eventIds.
   */
  java.util.List<Integer> getEventIdsList();
  /**
   * <code>repeated int32 eventIds = 1;</code>
   * @return The count of eventIds.
   */
  int getEventIdsCount();
  /**
   * <code>repeated int32 eventIds = 1;</code>
   * @param index The index of the element to return.
   * @return The eventIds at the given index.
   */
  int getEventIds(int index);
}
