// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package Calendar.ds.service2;

public interface ResponseMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.ResponseMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>repeated .service2.Appointment appointments = 2;</code>
   */
  java.util.List<Appointment>
      getAppointmentsList();
  /**
   * <code>repeated .service2.Appointment appointments = 2;</code>
   */
  Appointment getAppointments(int index);
  /**
   * <code>repeated .service2.Appointment appointments = 2;</code>
   */
  int getAppointmentsCount();
  /**
   * <code>repeated .service2.Appointment appointments = 2;</code>
   */
  java.util.List<? extends AppointmentOrBuilder>
      getAppointmentsOrBuilderList();
  /**
   * <code>repeated .service2.Appointment appointments = 2;</code>
   */
  AppointmentOrBuilder getAppointmentsOrBuilder(
      int index);
}
