// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package Calendar.ds.service2;

public final class Service2Impl {
  private Service2Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_eventId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_eventId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_Appointment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_Appointment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_ResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_ResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016service2.proto\022\010service2\032\033google/proto" +
      "buf/empty.proto\"\025\n\007eventId\022\n\n\002id\030\001 \001(\005\"]" +
      "\n\013Appointment\022\n\n\002id\030\001 \001(\005\022\r\n\005title\030\002 \001(\t" +
      "\022\016\n\006detail\030\003 \001(\t\022\021\n\toccurTime\030\004 \001(\t\022\020\n\010r" +
      "eminder\030\005 \001(\t\"D\n\010Response\022\014\n\004code\030\001 \001(\005\022" +
      "*\n\013appointment\030\002 \001(\0132\025.service2.Appointm" +
      "ent\"\037\n\017ResponseMessage\022\014\n\004code\030\001 \001(\0052\207\002\n" +
      "\010Service2\0229\n\010addEvent\022\025.service2.Appoint" +
      "ment\032\022.service2.Response\"\0000\001\022=\n\013deleteEv" +
      "ent\022\021.service2.eventId\032\031.service2.Respon" +
      "seMessage\"\000\022A\n\013updateEvent\022\025.service2.Ap" +
      "pointment\032\031.service2.ResponseMessage\"\000\022>" +
      "\n\tgetEvents\022\026.google.protobuf.Empty\032\025.se" +
      "rvice2.Appointment\"\0000\001B&\n\024Calendar.ds.se" +
      "rvice2B\014Service2ImplP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_service2_eventId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service2_eventId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_eventId_descriptor,
        new String[] { "Id", });
    internal_static_service2_Appointment_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service2_Appointment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_Appointment_descriptor,
        new String[] { "Id", "Title", "Detail", "OccurTime", "Reminder", });
    internal_static_service2_Response_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service2_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_Response_descriptor,
        new String[] { "Code", "Appointment", });
    internal_static_service2_ResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service2_ResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_ResponseMessage_descriptor,
        new String[] { "Code", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
