// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package Login.ds.service1;

public interface RequestMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.RequestMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 2;</code>
   * @return The password.
   */
  String getPassword();
  /**
   * <code>string password = 2;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
