// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package Login.ds.service1;

public final class Service1Impl {
  private Service1Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_RequestMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_RequestMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_ResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_ResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016service1.proto\022\010service1\032\033google/proto" +
      "buf/empty.proto\"4\n\016RequestMessage\022\020\n\010use" +
      "rname\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"\037\n\017Respons" +
      "eMessage\022\014\n\004code\030\001 \001(\0052\317\001\n\010Service1\022@\n\005l" +
      "ogin\022\030.service1.RequestMessage\032\031.service" +
      "1.ResponseMessage\"\000(\001\022A\n\006signup\022\030.servic" +
      "e1.RequestMessage\032\031.service1.ResponseMes" +
      "sage\"\000(\001\022>\n\007isLogin\022\026.google.protobuf.Em" +
      "pty\032\031.service1.ResponseMessage\"\000B#\n\021Logi" +
      "n.ds.service1B\014Service1ImplP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_service1_RequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service1_RequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_RequestMessage_descriptor,
        new String[] { "Username", "Password", });
    internal_static_service1_ResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service1_ResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_ResponseMessage_descriptor,
        new String[] { "Code", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
