// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package Reminder.ds.service3;

public interface IDOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.ID)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 ID = 1;</code>
   * @return The iD.
   */
  int getID();
}
