// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package Reminder.ds.service3;

/**
 * Protobuf type {@code service3.ReminderId}
 */
public final class ReminderId extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:service3.ReminderId)
    ReminderIdOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReminderId.newBuilder() to construct.
  private ReminderId(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReminderId() {
    iD_ = emptyIntList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ReminderId();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Service3Impl.internal_static_service3_ReminderId_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Service3Impl.internal_static_service3_ReminderId_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ReminderId.class, Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.IntList iD_;
  /**
   * <code>repeated int32 ID = 1;</code>
   * @return A list containing the iD.
   */
  @Override
  public java.util.List<Integer>
      getIDList() {
    return iD_;
  }
  /**
   * <code>repeated int32 ID = 1;</code>
   * @return The count of iD.
   */
  public int getIDCount() {
    return iD_.size();
  }
  /**
   * <code>repeated int32 ID = 1;</code>
   * @param index The index of the element to return.
   * @return The iD at the given index.
   */
  public int getID(int index) {
    return iD_.getInt(index);
  }
  private int iDMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getIDList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(iDMemoizedSerializedSize);
    }
    for (int i = 0; i < iD_.size(); i++) {
      output.writeInt32NoTag(iD_.getInt(i));
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < iD_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(iD_.getInt(i));
      }
      size += dataSize;
      if (!getIDList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      iDMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ReminderId)) {
      return super.equals(obj);
    }
    ReminderId other = (ReminderId) obj;

    if (!getIDList()
        .equals(other.getIDList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getIDCount() > 0) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getIDList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ReminderId parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ReminderId parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ReminderId parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ReminderId parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ReminderId parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ReminderId parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ReminderId parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ReminderId parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ReminderId parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ReminderId parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ReminderId parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ReminderId parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ReminderId prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code service3.ReminderId}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:service3.ReminderId)
      ReminderIdOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Service3Impl.internal_static_service3_ReminderId_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Service3Impl.internal_static_service3_ReminderId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ReminderId.class, Builder.class);
    }

    // Construct using Reminder.ds.service3.ReminderId.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      iD_ = emptyIntList();
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Service3Impl.internal_static_service3_ReminderId_descriptor;
    }

    @Override
    public ReminderId getDefaultInstanceForType() {
      return ReminderId.getDefaultInstance();
    }

    @Override
    public ReminderId build() {
      ReminderId result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ReminderId buildPartial() {
      ReminderId result = new ReminderId(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(ReminderId result) {
      if (((bitField0_ & 0x00000001) != 0)) {
        iD_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.iD_ = iD_;
    }

    private void buildPartial0(ReminderId result) {
      int from_bitField0_ = bitField0_;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ReminderId) {
        return mergeFrom((ReminderId)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ReminderId other) {
      if (other == ReminderId.getDefaultInstance()) return this;
      if (!other.iD_.isEmpty()) {
        if (iD_.isEmpty()) {
          iD_ = other.iD_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureIDIsMutable();
          iD_.addAll(other.iD_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int v = input.readInt32();
              ensureIDIsMutable();
              iD_.addInt(v);
              break;
            } // case 8
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureIDIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                iD_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            } // case 10
            default: {
//              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
//                done = true; // was an endgroup tag
//              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.IntList iD_ = emptyIntList();
    private void ensureIDIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        iD_ = mutableCopy(iD_);
        bitField0_ |= 0x00000001;
      }
    }
    /**
     * <code>repeated int32 ID = 1;</code>
     * @return A list containing the iD.
     */
    public java.util.List<Integer>
        getIDList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(iD_) : iD_;
    }
    /**
     * <code>repeated int32 ID = 1;</code>
     * @return The count of iD.
     */
    public int getIDCount() {
      return iD_.size();
    }
    /**
     * <code>repeated int32 ID = 1;</code>
     * @param index The index of the element to return.
     * @return The iD at the given index.
     */
    public int getID(int index) {
      return iD_.getInt(index);
    }
    /**
     * <code>repeated int32 ID = 1;</code>
     * @param index The index to set the value at.
     * @param value The iD to set.
     * @return This builder for chaining.
     */
    public Builder setID(
        int index, int value) {
      
      ensureIDIsMutable();
      iD_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 ID = 1;</code>
     * @param value The iD to add.
     * @return This builder for chaining.
     */
    public Builder addID(int value) {
      
      ensureIDIsMutable();
      iD_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 ID = 1;</code>
     * @param values The iD to add.
     * @return This builder for chaining.
     */
    public Builder addAllID(
        Iterable<? extends Integer> values) {
      ensureIDIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, iD_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 ID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearID() {
      iD_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:service3.ReminderId)
  }

  // @@protoc_insertion_point(class_scope:service3.ReminderId)
  private static final ReminderId DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ReminderId();
  }

  public static ReminderId getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReminderId>
      PARSER = new com.google.protobuf.AbstractParser<ReminderId>() {
    @Override
    public ReminderId parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ReminderId> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ReminderId> getParserForType() {
    return PARSER;
  }

  @Override
  public ReminderId getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

