// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package Reminder.ds.service3;

public interface ReminderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.Reminder)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string year = 1;</code>
   * @return The year.
   */
  String getYear();
  /**
   * <code>string year = 1;</code>
   * @return The bytes for year.
   */
  com.google.protobuf.ByteString
      getYearBytes();

  /**
   * <code>string month = 2;</code>
   * @return The month.
   */
  String getMonth();
  /**
   * <code>string month = 2;</code>
   * @return The bytes for month.
   */
  com.google.protobuf.ByteString
      getMonthBytes();

  /**
   * <code>string day = 3;</code>
   * @return The day.
   */
  String getDay();
  /**
   * <code>string day = 3;</code>
   * @return The bytes for day.
   */
  com.google.protobuf.ByteString
      getDayBytes();

  /**
   * <code>string hour = 4;</code>
   * @return The hour.
   */
  String getHour();
  /**
   * <code>string hour = 4;</code>
   * @return The bytes for hour.
   */
  com.google.protobuf.ByteString
      getHourBytes();

  /**
   * <code>string min = 5;</code>
   * @return The min.
   */
  String getMin();
  /**
   * <code>string min = 5;</code>
   * @return The bytes for min.
   */
  com.google.protobuf.ByteString
      getMinBytes();

  /**
   * <code>string sec = 6;</code>
   * @return The sec.
   */
  String getSec();
  /**
   * <code>string sec = 6;</code>
   * @return The bytes for sec.
   */
  com.google.protobuf.ByteString
      getSecBytes();

  /**
   * <code>int32 ID = 7;</code>
   * @return The iD.
   */
  int getID();
}
