// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package Reminder.ds.service3;

public interface ReminderIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.ReminderId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 ID = 1;</code>
   * @return A list containing the iD.
   */
  java.util.List<Integer> getIDList();
  /**
   * <code>repeated int32 ID = 1;</code>
   * @return The count of iD.
   */
  int getIDCount();
  /**
   * <code>repeated int32 ID = 1;</code>
   * @param index The index of the element to return.
   * @return The iD at the given index.
   */
  int getID(int index);
}
