// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package Reminder.ds.service3;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
