// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package Appointment.ds.service2;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>.service2.Appointment appointment = 2;</code>
   * @return Whether the appointment field is set.
   */
  boolean hasAppointment();
  /**
   * <code>.service2.Appointment appointment = 2;</code>
   * @return The appointment.
   */
  Appointment getAppointment();
  /**
   * <code>.service2.Appointment appointment = 2;</code>
   */
  AppointmentOrBuilder getAppointmentOrBuilder();
}
