// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.service2;

public final class Service2Impl {
  private Service2Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_AppointmentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_AppointmentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_Appointment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_Appointment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_ResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_ResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016service2.proto\022\010service2\"A\n\022Appointmen" +
      "tRequest\022+\n\014appointments\030\001 \003(\0132\025.service" +
      "2.Appointment\"K\n\013Appointment\022\n\n\002id\030\001 \001(\005" +
      "\022\r\n\005title\030\002 \001(\t\022\016\n\006detail\030\003 \001(\t\022\021\n\toccur" +
      "Time\030\004 \001(\003\"\037\n\017ResponseMessage\022\014\n\004code\030\001 " +
      "\001(\0052T\n\010Service2\022H\n\013service2_do\022\034.service" +
      "2.AppointmentRequest\032\031.service2.Response" +
      "Message\"\000B\035\n\013ds.service2B\014Service2ImplP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_service2_AppointmentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service2_AppointmentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_AppointmentRequest_descriptor,
        new String[] { "Appointments", });
    internal_static_service2_Appointment_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service2_Appointment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_Appointment_descriptor,
        new String[] { "Id", "Title", "Detail", "OccurTime", });
    internal_static_service2_ResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service2_ResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_ResponseMessage_descriptor,
        new String[] { "Code", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
